lch_admin_menu:
  resource: "@LchAdminBundle/Resources/config/routing/menu.yml"
  prefix: /menu

lch_admin_media:
  resource: "@LchAdminBundle/Resources/config/routing/media.yml"
  prefix: /media

lch_admin_tag:
  resource: "@LchAdminBundle/Resources/config/routing/tag.yml"
  prefix: /tag