parameters:
  lch.admin.menu_builder.class: 'Lch\AdminBundle\Menu\MenuBuilder'

services:
  lch.admin.menu_builder.admin:
    class: "%lch.admin.menu_builder.class%"
    arguments: ["@knp_menu.factory", "@security.token_storage", "@event_dispatcher"]
    tags:
      - { name: knp_menu.menu_builder, method: adminMainMenu, alias: main }

  lch.admin.generate_menu:
    class: Lch\AdminBundle\Listener\Menu\AdminMenuListener
    arguments: ['@translator']
    tags:
      - { name: kernel.event_listener, event: lch.admin.generate_menu, method: onAdminMenuGeneration, priority: 90 }
    lazy: true

  lch.admin.menu.list.subscriber:
    class: Lch\AdminBundle\Listener\Menu\MenusListSubscriber
    arguments: ['@translator']
    tags:
      - { name: kernel.event_subscriber }
    lazy: true

  lch.admin.tag.list.subscriber:
      class: Lch\AdminBundle\Listener\Menu\TagsListSubscriber
      arguments: ['@translator']
      tags:
        - { name: kernel.event_subscriber }
      lazy: true