parameters:
    lch.admin.twig.extension: 'LCH\AdminBundle\Twig\Extension\LCHAdminExtension'


services:
#    LCH.admin.menu_builder.super_admin:
#        class: LCH\AdminBundle\Menu\MenuBuilder
#        arguments: ["@knp_menu.factory", "@security.token_storage", "@service_container"]
#        tags:
#            - { name: knp_menu.menu_builder, method: adminMainMenu, alias: main }

    # Twig Extensions
    lch.twig_extension.admin:
        class: "%lch.admin.twig.extension%"
        public: false
        arguments: ["@doctrine.orm.entity_manager", '@session', "@twig", "@event_dispatcher", "@security.token_storage", '@translator']
        tags:
            - { name: twig.extension }
        lazy: true